// <auto-generated />
namespace web_application_with_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class After_add_albums_controller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(After_add_albums_controller));
        
        string IMigrationMetadata.Id
        {
            get { return "201704040647214_After_add_albums_controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
